server:
  port: 5000
spring:
  data:
    mongodb:
      database: MovieBooking
      host: localhost
      port: 27017 
      url: mongodb://priya62:priya6284@docdb-2023-07-29-03-37-44priya.cluster-c2rb9nk5vhd4.us-east-1.docdb.amazonaws.com:27017/moviebookingpriya?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      
